spring.application.name=smart-closet

spring.freemarker.suffix=.ftl
spring.freemarker.charset=UTF-8
spring.freemarker.cache=false
spring.freemarker.template-loader-path=classpath:/templates/

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/smartcloset
spring.datasource.username=elvina
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379
weather.api.key=9e62c82005948ccb39032dec9ca0b90c